
trigger:
- main
pool:
  vmImage: unbuntu-latest
variables:
  buildConfiguration: 'Release'
steps:
- script: dotnet buidl --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildconfiguration)'